name: Build

on:
  push:
    branches:
      - main
      - master
  pull_request:

env:
  IMAGE_NAME: theknarf/shell

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build . --tag $IMAGE_NAME
